name: OpenAPI Generate Client

on:
  repository_dispatch:
    types: generate-client
    inputs:
      templateLocation:
        description: The path to the openapi template directory.
        required: false

jobs:
  generate-client:
    runs-on: ubuntu-latest
    name: Generate Client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove Generated Files
        continue-on-error: true
        run: xargs -I{} rm -rf "{}" < .openapi-generator/FILES
      - name: Download OpenAPI artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.CLONE_PAT}}
          workflow: release.yml
          workflow_conclusion: success
          name: openapi-spec
          repo: NekoFluff/alex-api
      - name: Write Spec
        run: |
          if [[ ! -z "${{ inputs.payload }}" ]]
          then
            echo "${{ inputs.payload }}" | base64 --decode > openapi.yaml
          fi
          cat openapi.yaml
      - name: Read Spec
        id: spec
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: openapi.yaml
          title: info.title
          version: info.version
      - name: Set Config File
        id: set-config
        run: |
          echo 'OPENAPI_CONFIG=-c config.yml' >> $GITHUB_OUTPUT
      - name: Set Template Dir
        id: set-template
        if: ${{ inputs.templateLocation }}
        run: |
          echo 'OPENAPI_TEMPLATE=-t ${{ inputs.templateLocation }}' >> $GITHUB_OUTPUT
      - name: Generate Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-node
          generator-tag: v6.4.0
          openapi-file: openapi.yaml
          config-file: config.yml
          command-args: |
            --git-user-id ${{ github.repository_owner }} --git-repo-id ${{ github.event.repository.name }} \
            ${{ steps.set-config.outputs.OPENAPI_CONFIG }} \
            ${{ steps.set-template.outputs.OPENAPI_TEMPLATE }} \
            -o .
      - name: Remove Spec
        run: rm -f openapi.yaml
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "${{ steps.spec.outputs.title }} ${{ steps.spec.outputs.version }}"
          tag: ${{ steps.spec.outputs.version }}
