name: OpenAPI Generate Client

on:
  repository_dispatch:
    types: generate-client
    inputs:
      configLocation:
        description: The filepath to the openapi config file.
        required: true
        type: string
      templateLocation:
        description: The path to the openapi template directory.
        required: false

jobs:
  generate-client:
    runs-on: ubuntu-latest
    name: Generate Client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Download Release Asset
#         uses: dsaltares/fetch-gh-release-asset@master
#         if: "${{ github.event.client_payload.release }}"
#         with:
#           repo: NekoFluff/alex-api
#           version: "tags/v${{ github.event.client_payload.release }}"
#           file: openapi.yaml
#           target: openapi.yaml
#           token: ${{ secrets.CLONE_PAT }}
      - name: Download OpenAPI artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if the artifact is from a different repo
          # Required, if the repo is private a Personal Access Token with `repo` scope is needed
          github_token: ${{secrets.CLONE_PAT}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: generate.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          workflow_conclusion: success
          # Optional, will get head commit SHA
          # pr: ${{github.event.pull_request.number}}
          # Optional, no need to specify if PR is
          # commit: ${{github.event.pull_request.head.sha}}
          # Optional, will use the specified branch. Defaults to all branches
          # branch: master
          # Optional, defaults to all types
          # event: push
          # Optional, will use specified workflow run
          # run_id: 1122334455
          # Optional, run number from the workflow
          # run_number: 34
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them into respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: openapi-spec
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          # path: extract_here
          # Optional, defaults to current repo
          repo: NekoFluff/alex-api
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          # check_artifacts:  false
          # Optional, search for the last workflow run whose stored an artifact named as in `name` input
          # default false
          # search_artifacts: false
          # Optional, choose to skip unpacking the downloaded artifact(s)
          # default false
          # skip_unpack: false
          # Optional, choose how to exit the action if no artifact is found
          # can be one of:
          #  "fail", "warn", "ignore"
          # default fail
          # if_no_artifact_found: fail
      - name: Write Spec
        run: |
          if [[ ! -z "${{ inputs.payload }}" ]]
          then
            echo "${{ inputs.payload }}" | base64 --decode > openapi.yaml
          fi
          cat openapi.yaml
      - name: Read Spec
        id: spec
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: openapi.yaml
          title: info.title
          version: info.version
      - name: Set Config File
        id: set-config
        if: ${{ inputs.configLocation }}
        run: |
          echo 'OPENAPI_CONFIG=-c ${{ inputs.configLocation }}' >> $GITHUB_OUTPUT
      - name: Set Template Dir
        id: set-template
        if: ${{ inputs.templateLocation }}
        run: |
          echo 'OPENAPI_TEMPLATE=-t ${{ inputs.templateLocation }}' >> $GITHUB_OUTPUT
      - name: Generate Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          generator-tag: ${{ github.event.client_payload.release }}
          openapi-file: openapi.yaml
          command-args: |
            --git-user-id ${{ github.repository_owner }} --git-repo-id ${{ github.event.repository.name }} \
            --package-name alex-api-typescript-client \
            ${{ steps.set-config.outputs.OPENAPI_CONFIG }} \
            ${{ steps.set-template.outputs.OPENAPI_TEMPLATE }} \
            -o .
      - name: Remove Spec
        run: rm -f openapi.yaml
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "${{ steps.spec.outputs.title }} ${{ steps.spec.outputs.version }}"
          tag: ${{ steps.spec.outputs.version }}
